### ISSUE TITLE
Compile static library while requiring a dynamic one

### ISSUE THREAD

**Issue by ngeiswei** [PaulBatchelor/Spigot#2]
## Problem

The Spigot project page gives the following sp code to use Spigot

```
 _spigot "./spigot.so" fl
 0 120 4 clock 1 "foo.rnt" _spigot fe
 # Do stuff here.
 _spigot fc
```

However the library compiled by the make file (on linux anyway)

```
make linux
```

generates a static library `libspigot.a`.

Attempting to load the static library of course fails with the following message

```
Error loading spigot: ./libspigot.a: invalid ELF header
```

## What should be done

I suppose the right course of actions is to change the Makefile to create a dynamic library, but maybe there's something else.

**Comment by PaulBatchelor** [comment]
The Spigot Documentation is a little out of date. I *used* to have support for a plugin, but removed it. When using it, I found that things would occasionally crash in a live coding setting. Spigot is now only run as a standalone executable.

Try running `./spigot ex/tek.sp` and see if that works.

**Comment by ngeiswei** [comment]
I tried but I'm getting a segfault
```bash
nilg@sofia-desktop:~/Sources/Spigot$ ./spigot ex/tek.sp 
Loading file ex/tekscore.rnt
play: "1",
Segmentation fault (core dumped)
```

**Comment by PaulBatchelor** [comment]
can you try compiling sporth using the dev branch? it is very important that you do a full clean with "make clean" before rebuilding.

**Comment by ngeiswei** [comment]
Awesome, it works!!! Thanks.

**Comment by PaulBatchelor** [comment]
Cool! I've removed the mention of the plugin in the project page, and I have updated the example code as well.
